services:
  - type: web
    name: losgatosnegros
    runtime: python-3
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.render.com,localhost"
      - key: losgatosdb_POSTGRES_DATABASE
        value: postgres
      - key: losgatosdb_POSTGRES_USER
        value: postgres.duldrmfptypuvkuxpxyh
      - key: losgatosdb_POSTGRES_PASSWORD
        value: y6AVuJ1dnZYfFBqP
      - key: losgatosdb_POSTGRES_HOST
        value: db.duldrmfptypuvkuxpxyh.supabase.co
      - key: losgatosdb_POSTGRES_PORT
        value: "5432"
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://duldrmfptypuvkuxpxyh.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bGRybWZwdHlwdXZrdXhweHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNzQxNjQsImV4cCI6MjA3ODY1MDE2NH0.FBRpM1bw7NXHVXyIDVTHPvMsURf0hIYzAGnKb7W3yXw
      - key: losgatosdb_SUPABASE_URL
        value: https://duldrmfptypuvkuxpxyh.supabase.co
      - key: losgatosdb_SUPABASE_JWT_SECRET
        value: 58Or/hfE3Y+TGuNf1b2MqCE6tFgRYjZhZH+aF0BoBktBqBxMrVykeoC1LuXL/No6rIfZuKJrzGwGFqxnYufEGA==
      - key: losgatosdb_SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bGRybWZwdHlwdXZrdXhweHloIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzA3NDE2NCwiZXhwIjoyMDc4NjUwMTY0fQ.A3dXTH6-VKdX1-_QGHqNye3gKk-trYSsJDAHQuNQygs
